### ISSUE TITLE
Application gets stuck when inject after adding Dragon Knight's items

### ISSUE THREAD

**Issue by ducbh62git** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#13]
Hi Aldrin,

- The application gets stuck at `Waiting for all Cosmetic Extraction to Finish PID=` phase when I add some DK's items (except new persona) like below:
<img width="665" alt="issue dragon knight" src="https://user-images.githubusercontent.com/69949959/129469218-9527d5ba-3e3a-4642-b611-939d45f96d6f.png">

I tried to uncheck all DK's items and add other heroes item then this does not get stuck anymore. So I think this from DK's items.

- Second, if a new version is released. How to update without deleting the current one in my machine ?

Finally, I want to thank you for keep great working on this perfect tool. I appreciate your works.

Thank you.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Hello, There seems to be a BUG on the PID identification, and I would fix it right away. What Windows version are you using?

- Also Please Download WinRAR and Archive your WHOLE DOTA2 MOD Master Folder. Then upload it here so that I can test it out
- Also please attach your database file here so that I can investigate it too.

Thanks for reaching out for me

**Comment by ducbh62git** [comment]
> Hello, There seems to be a BUG on the PID identification, and I would fix it right away. What Windows version are you using?
> 
> * Also Please Download WinRAR and Archive your WHOLE DOTA2 MOD Master Folder. Then upload it here so that I can test it out
> * Also please attach your database file here so that I can investigate it too.
> 
> Thanks for reaching out for me

Thanks for replying me. Here is the link to download my snapshot (v2.9.3): [Download Link](https://drive.google.com/file/d/1o2b-GBVSI8HIdOVKfV_BNWCyeHkNA45m/view?usp=sharing)

My DB is large because I added items for all heroes but I think it make sure that this tool is perfect and we can test it out on all heroes in the game

Here is the list of items that cause the error:

- Monkey King Arcana's style count
- Dragon Knight's items (except new persona)
- Prismatic Grace's style count (Naga Siren's items)

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Try in change compatibility mode of DOTA2 MOD Master.

1. Right click **DOTA2 MOD Master.exe** then left click *Properties*
2. Under the Compatibility, choose an certain OS version starting from the version lower than yours, downwards**(NOTE: Do not Choose Windows Vista)**. Example, if you are using Windows 10, try windows 8.1 compatibility, if not working try windows 8, then 7, then XP.

**Comment by ducbh62git** [comment]
After changing compatibility mode, the application runs too slow and still gets stuck in same case. And here is the screenshot when I get stuck in v2.9.4
<img width="586" alt="error" src="https://user-images.githubusercontent.com/69949959/129944399-4eca112a-f5f9-4cb1-91ac-ab4e55d8027a.png">

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
attach your database file here. I cannot redownload your link above.

**Comment by ducbh62git** [comment]
Github does not accept your DB file extension so I put it in Google Drive: [Download Link](https://drive.google.com/file/d/10sdd3ZEswruNDH81cOZMrNfETfit7M0x/view?usp=sharing)

**Comment by ducbh62git** [comment]
> I Identified the Bug from Monkey king. It seems that its material file failed to extract for some reason that I should investigate. It will be fixed on the next version. Thanks you for your effort on identifying the cause of a bug.

So glad to hea

**Comment by ducbh62git** [comment]
> I Identified the Bug from Monkey king. It seems that its material file failed to extract for some reason that I should investigate. It will be fixed on the next version. Thanks you for your effort on identifying the cause of a bug.

So glad to hear that. Thank you!
