### ISSUE TITLE
Is there any way to change the color of prismatic gem?

### ISSUE THREAD

**Issue by shikiroot** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#14]
Hi Aldrin, first of all, thanks for your great work, to built this awesome tool. When I used that to inject TB's arcana, the arcana does not have prismatic gem, and the color is blue. So I am wondering is there any way to change the color of prismatic gem? Thank you again!

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
I haven't implemented prismatic Gem Modification in this tool, because the prismatic gems have dynamic parameters at items_game.txt which makes parsing hard and unstable. Sorry.
