### ISSUE TITLE
colors are missing (Fixed on v2.9.2)

### ISSUE THREAD

**Issue by HyperDrake** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#2]
rarity colors are all gone in lastest patch. Very hard to see 

-

**Comment by persi127** [comment]
Si es verdad, así es un poco más complicado

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
> rarity colors are all gone in lastest patch. Very hard to see

Fixed on v2.9.2, Thank you for reporting.

**Comment by ducbh62git** [comment]
> > rarity colors are all gone in lastest patch. Very hard to see
> 
> Fixed on v2.9.2, Thank you for reporting.

It's missing again in v2.9.3. Please fix it
