### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by GANGAN2** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#20]
my pc see it as a virus

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Check the [source code](https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/blob/master/AJOM%20Innovations/AJOM's%20DOTA2%20MOD%20Master/Open%20Source%20Code/AJOM's%20DOTA2%20MOD%20Master.ahk) for anything malicious.

Related to issue #12
