### ISSUE TITLE
Rubick Arcana problem

### ISSUE THREAD

**Issue by novakhayne** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#21]
First of all, thank you for the program!

I am having an issue with The Magus Cypher. If I inject it, it changes all spells for all heroes, not just Rubick. For example, if I inject the arcana, Enigma's black hole is now in the Rubick style. Can this be fixed or do I have to remove the arcana?

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
At handy injection > used items database

1) Right click magus cypher
2) left click decrease priority
3) keep on decreasing its priority until it is on the **first row**

This will unprioritize arcana rubick's greeny spells.

The current tool does not have a feature that turns of custom spells of cosmetic items. Maybe in the future it will be implemented.

**Comment by novakhayne** [comment]
Okay I'll give that a try. 

I'm also having issues trying to update. It downloads everything and then it tells me it's been installed and for me to restart the program. After clicking 'Yes' nothing happens and when I open the program again it prompts me to update again. If I deny the update, it opens the program and works fine but it's stuck in v2.6.3. I messed around with Windows Defender but nothing is working. Any ideas on what's wrong?

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
I can't reproduce the auto-update bug you are experiencing. It works fine.


About the rubick abilities, A new Feature **Extract Hero Visuals** will be implemented on the next version

**Comment by novakhayne** [comment]
Okay, no problem. Luckily I'm building a new computer today so once that's done I'll try it on the new one and we'll see what happens. Any reason why you think this might be happening?

**Comment by novakhayne** [comment]
Still have the same issue and cannot update the program from 2.6.3. I disabled virus and firewall protections, ran the program as an administrator and nothing. What should I do?

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Delete the whole DOTA2 MOD Master then Download the [newer version](https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/archive/refs/heads/master.zip).

**Comment by novakhayne** [comment]
Excellent, that downloaded the right version, thank you! Once you release a new update I will let you know if there are any issues left with updating. :)

Thanks again for the program!
