### ISSUE TITLE
Stuck in Shutkik Method: Creating pak01_dir1.vpk

### ISSUE THREAD

**Issue by LeoSel25** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#22]
Whenever I try any version of the mod it's always stuck in "Stuck in Shutkik Method: Creating pak01_dir1.vpk"

I don't know what to do

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
What DOTA2 MOD Master version are you using?

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Make sure you are using DOTA2 MOD Master v2.9.6 or above version.
