### ISSUE TITLE
Extracting Library Files its not gonna stop

### ISSUE THREAD

**Issue by glorydoto** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#24]
![2021-11-02 (8)](https://user-images.githubusercontent.com/66716768/139833461-534c5530-2ccc-4e50-84ba-007f74e51b19.png)
Extracting Library Files its taking so long time its not gonna stop please fix it .And can you make Terrorblade arcanas colors please

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
> ![2021-11-02 (8)](https://user-images.githubusercontent.com/66716768/139833461-534c5530-2ccc-4e50-84ba-007f74e51b19.png) Extracting Library Files its taking so long time its not gonna stop please fix it .

Make sure to fully install DOTA2 MOD Master:
1) Uninstall your Current DOTA2 MOD Master.
2) Install [this link](https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/archive/refs/heads/master.zip). Make sure to extract the whole folder.
3) Run DOTA2 MOD Master _as Administrator_.
4) Make sure that your AntiVirus isn't interfering the operation of this tool. It is better to **white list** the whole folder of DOTA2 MOD Master.
5) make sure you have all the [plugins](https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/tree/master/AJOM%20Innovations/AJOM's%20DOTA2%20MOD%20Master/Plugins) of DOTA2 MOD Master.


> And can you make Terrorblade arcanas colors please

Maybe in the future, I'm not that motivated on adding some optional features like this.

**Comment by glorydoto** [comment]
sorry its happening again. even i turned off my antivirus.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
You must be having an OS Formatting problem. There are 3 Executable files our there:
1. x64
2. x86
3. x86 ANSI

Try using the **x86** DOTA2 MOD Master, if the problem still persists then try the **x86 ANSI**.

**Comment by glorydoto** [comment]
they all not working

**Comment by glorydoto** [comment]
![image](https://user-images.githubusercontent.com/66716768/140399506-c59ed70f-ffa5-4d8f-b1c0-49ab99712565.png)
is that actual problem?

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Screenshot these folders that are found inside the **DOTA2 MOD Master/** folder:
1. **Library/**
2. **Plugins/**
3. **Plugins/hllib246/bin/x64/**
4. **Plugins/hllib246/bin/x86/**
5. Main directory(DOTA2 MOD Master folder)

Attach all those five screenshots on your reply.

**Comment by glorydoto** [comment]
![image](https://user-images.githubusercontent.com/66716768/140405013-2f193c4f-f0e3-4236-bf05-6c4076db335a.png)
![image](https://user-images.githubusercontent.com/66716768/140405023-15ce46dc-be14-4e9f-9107-c46d03b172ce.png)
![image](https://user-images.githubusercontent.com/66716768/140405036-6dc46214-738b-4fe9-a11c-0fba7205ee9b.png)
![image](https://user-images.githubusercontent.com/66716768/140405047-d645d220-5d15-4c8e-b237-84085c01b884.png)
![image](https://user-images.githubusercontent.com/66716768/140405060-9a06ba08-68fe-4714-8450-9d5ab40fd9d3.png)

**Comment by glorydoto** [comment]
![image](https://user-images.githubusercontent.com/66716768/140405346-05ec2780-0acb-469e-9944-29f2a96299ec.png)

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Right click DOTA2 MOD Master > properties > compatibility, then try changing it into other OS version that might work(windows 8, if not then windows 7, ect.).

I've received multiple issues on windows 10 users. I haven't tested the tool at windows 10 since I use windows 7 and windows 8.1 .

**Comment by glorydoto** [comment]
i tried its not working

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
I can't help you on resolving your windows 10 issue anymore due to my lack of resources simulating windows 10. For now you can either try finding a solution for this problem by yourself or use another tool other than DOTA2 MOD Master. If you find a way to fix it, you might as well share it here so that other users would know how to deal with this issue.

**Comment by glorydoto** [comment]
its looping because my library file was empty and i fixed it. Btw i l really love your mods

**Comment by ducbh62git** [comment]
> ![image](https://user-images.githubusercontent.com/66716768/140399506-c59ed70f-ffa5-4d8f-b1c0-49ab99712565.png)
> is that actual problem?

Where did you turn off antivirus?
Go Virus and threat protection settings > turn off realtime-protection
This must be turned off
