### ISSUE TITLE
Memory limit reached

### ISSUE THREAD

**Issue by AKA2320** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#27]
When I launch the application this message pops up, and after I close the dialog the app is froze/stuck on "Saving contents of ListView: blinkeffectchoice" 
![image](https://user-images.githubusercontent.com/67814290/146134651-29320d7c-47f5-49e7-bea8-d182f7fabee6.png)

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
It will be fixed on the next update. Thanks for reporting

**Comment by echoaldemo** [comment]
i was just gonna file this issue 😁 hoping for drow ranger arcana on the next update 🥺🥺

**Comment by ducbh62git** [comment]
> i was just gonna file this issue 😁 hoping for drow ranger arcana on the next update 🥺🥺

Yes. v2.9.9 will be interesting with new arcana and immortals

**Comment by leo125604** [comment]
Hi bro When can we download the update?

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
@ducbh62git 
There is no need to wait for version 2.9.9 just to add the new arcana and immortals. You can add that arcana and immortals as part of your skin collection(database) yourself. I will upload my Personal Database File next week that will be available for everyone, together with the new version 2.9.9.

@leo125604 
I will update the script next week(since I don't have free time for now) which will also include radiant/dire siege engine skin at Miscellaneous.

**Comment by leo125604** [comment]
> @ducbh62git There is no need to wait for version 2.9.9 just to add the new arcana and immortals. You can add that arcana and immortals as part of your skin collection(database) yourself. I will upload my Personal Database File next week that will be available for everyone, together with the new version 2.9.9.
> 
> @leo125604 I will update the script next week(since I don't have free time for now) which will also include radiant/dire siege engine skin at Miscellaneous.
Thanks for your work bro , The version 2.9.8 don't working know ,i have tha same error , we would only wait the next version.

**Comment by teddfrandell19** [comment]
Hello Sir, AJOM, Been an avid user since 2018. May I know When will the update be? Thank you.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
On my christmas vacation, I'll release a new version. But for now, real life job comes first.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Although, if you are already eager to fix the memory limit bug so that you can use the tool once again:
1) browse **AJOM Innovations/DOTA2 MOD Master/Open Source Code/** folder. You will see a file named **AJOM's DOTA2 MOD Master.ahk**
2) Move(cut) the **AJOM's DOTA2 MOD Master.ahk** and place it at the root directory of this tool(where you can find the DOTA2 MOD Master application). The path will then become **AJOM Innovations/DOTA2 MOD Master/AJOM's DOTA2 MOD Master.ahk**
3) Open the **.ahk file(AJOM's DOTA2 MOD Master.ahk)** using any text editor(like notepad.exe).
4) make a new line by pressing the **Enter** button and then type `#MaxMem 4095`
5) save this modified .ahk file(press ctrl+s).
6) Install [Autohotkey Programming Language](https://www.autohotkey.com/download/ahk-install.exe) to your computer. This will allow you to run **.ahk files** like an application.
7) now double click **AJOM's DOTA2 MOD Master.ahk**(or right click that file then left click **launch using autohotkey**)
8) DOTA2 MOD Master will run like a normal application now.

**Comment by teddfrandell19** [comment]
![image](https://user-images.githubusercontent.com/96400252/146956789-f81dd692-6ee6-480f-bd04-69db0b6ee09c.png)
 I TRIED THIS SIR. THANK YOU IT'S WORKING NOW

**Comment by ducbh62git** [comment]
> Although, if you are already eager to fix the memory limit bug so that you can use the tool once again:
> 
> 1. browse **AJOM Innovations/DOTA2 MOD Master/Open Source Code/** folder. You will see a file named **AJOM's DOTA2 MOD Master.ahk**
> 2. Move(cut) the **AJOM's DOTA2 MOD Master.ahk** and place it at the root directory of this tool(where you can find the DOTA2 MOD Master application). The path will then become **AJOM Innovations/DOTA2 MOD Master/AJOM's DOTA2 MOD Master.ahk**
> 3. Open the **.ahk file(AJOM's DOTA2 MOD Master.ahk)** using any text editor(like notepad.exe).
> 4. make a new line by pressing the **Enter** button and then type `#MaxMem 4095`
> 5. save this modified .ahk file(press ctrl+s).
> 6. Install [Autohotkey Programming Language](https://www.autohotkey.com/download/ahk-install.exe) to your computer. This will allow you to run **.ahk files** like an application.
> 7. now double click **AJOM's DOTA2 MOD Master.ahk**(or right click that file then left click **launch using autohotkey**)
> 8. DOTA2 MOD Master will run like a normal application now.

I'm a programmer too. But I don't know about AutoHotKey yet. I think I will try to dive to it in the future. Hope I can co-work with you to develop this perfect tool and share the work with you.

**Comment by gandalfeblanco** [comment]
> ![image](https://user-images.githubusercontent.com/96400252/146956789-f81dd692-6ee6-480f-bd04-69db0b6ee09c.png) PROBÉ ESTO SEÑOR. GRACIAS ESTÁ FUNCIONANDO AHORA

teddfrandell19 how did you correct it ?, I tried and I get more errors.
![Captura](https://user-images.githubusercontent.com/96488230/146964758-4ae9798d-0fbb-4c9a-bc0a-f63d5842ddb3.PNG)

**Comment by ducbh62git** [comment]
> > ![image](https://user-images.githubusercontent.com/96400252/146956789-f81dd692-6ee6-480f-bd04-69db0b6ee09c.png) PROBÉ ESTO SEÑOR. GRACIAS ESTÁ FUNCIONANDO AHORA
> 
> teddfrandell19 how did you correct it ?, I tried and I get more errors. ![Captura](https://user-images.githubusercontent.com/96488230/146964758-4ae9798d-0fbb-4c9a-bc0a-f63d5842ddb3.PNG)

I've imported all cosmetics to heroes. I just added `#MaxMem 4095` at 1st line in the .ahk file
Maybe you added to wrong line.

**Comment by gandalfeblanco** [comment]
Could You send me screenshots for how yo do it? I'm just in the programming
process, please

**Comment by Tdatha** [comment]
The app is working with the fix as per usual, however, the skins have no particle effects on my end whatsoever. Can't have everything I guess, this will do though.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
@gandalfeblanco just follow my step by step process, you are receiving that error becase the script's code doesn't have `#MaxMem 4095` line at the beginning of the text.

@Tdatha try using other architecture of the application and Inject the MOD then tell me the results:
- (x64)
- (x86)
- (x86 ANSI)

@ducbh62git you can, although if you are already a programmer then It would be better for you to make an application that does the same operation as per this tool using the programming language you are accustomed to.

**Comment by ducbh62git** [comment]
Running as .ahk file is faster than running as .exe file. Does someone feel that ?

**Comment by Tdatha** [comment]
> 
Out of three architectures, only the latter (x86 ANSI) were able to launch. However, upon completing injecting the MOD, there was this error message, and the skins would still have no particle effects in-game. Here's AM as an example. 
![error](https://user-images.githubusercontent.com/96226969/147025299-5e814c50-3889-4cc6-9ebd-36d4a99e7009.png)
![am](https://user-images.githubusercontent.com/96226969/147025304-9e5c1df6-97cc-44b4-8f5d-db90b3905f01.png)

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
@Tdatha Have you tried using the .ahk file with `MaxMem 4095` line added?

If yes and the problem Still persists, upload the following files here on you next reply:
1) **Steam\steamapps\common\dota 2 beta\game\dota\gameinfo.gi** file
2) the whole DOTA2 MOD Master folder(compress it using winrar).

**Comment by Tdatha** [comment]
@Aldrin-John-Olaer-Manalansan thank you regardless. GitHub wont let me upload the entire MOD folder (compressed of course), any other way I can share it you?
[gameinfo.zip](https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/files/7760778/gameinfo.zip)

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
@Tdatha looking at your gameinfo.gi parameters, it seems that you uses other modding tool application besides DOTA2 MOD Master?

You might've been experiencing mod overriding conflict, try:
1) Delete **Steam\steamapps\common\dota 2 beta\game\dota\gameinfo.gi** file.
2) Verify Integrity Cache(using steam application > dota 2 > properties).

**Comment by Hieuphan2307** [comment]
I used other modding tool application besides DOTA2 MOD Master and then:
![image](https://user-images.githubusercontent.com/96197954/147252306-de3e85c2-5a2c-472d-a2f5-497cb776f4d7.png)
how to fix this error

**Comment by Hieuphan2307** [comment]
![image](https://user-images.githubusercontent.com/96197954/147264735-f8bb9e84-0c93-433b-a0f2-34db5f77140c.png)
how to fix it?
