### ISSUE TITLE
Generate only items_game.txt without models/material files

### ISSUE THREAD

**Issue by JawsKen98** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#28]
Im sorry Im not familiar with the program but is it possible to only make changes in items_game.txt with the current release? I only play with bots on local host and those extraction of models & materials really what makes the injection slow. Also how do I use migrate feature? Everytime I use it, my dota will give some error on launch
PS: my englis is not relly gud

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
The Old version of DOTA2 MOD Master Only modifies items_game.txt ... But as time passes by the tool improved a lot where it also supported cosmetic items extraction.

I agree that cosmetic items is what makes the Modding slower(not to mention that it consumes RAM that might Hang your computer). But Apparently, the Tool doesn't support an option to Only operate items_game.txt and not extract cosmetic files. I haven't though about it, maybe I'll add it on the next update. Thanks for suggesting
