### ISSUE TITLE
Error when opening x64 version

### ISSUE THREAD

**Issue by ikubaru92** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#29]
I got this error when opening the x64 version after the aghanim battle pass update
![Untitled](https://user-images.githubusercontent.com/90360020/147060899-ee5f514a-29a6-4806-8f95-43c8dc93906e.jpg)

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Related to ticket #27 . The bug be fixed on the next update(after christmas). Alternatively, you can fix it yourself by following this [workaround](https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/issues/27#issuecomment-998830009).
