### ISSUE TITLE
Some humble requests

### ISSUE THREAD

**Issue by ikubaru92** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#36]
Hello sir,

This is not to report any issue but would like to ask you if you can add all the Battlepass effects with as all the previous and upcoming battlepass teleport, radiance, phase boots, fog shader, eul, attack animation, blink dagger, aghanim and etc effects. Thanks for the tool

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Will be added on the next update.
