### ISSUE TITLE
Some hero animation return green color

### ISSUE THREAD

**Issue by lamdepzaihn98** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#38]
Some hero animation return green color for no reason, need help

Pangolier:
![image](https://user-images.githubusercontent.com/36037203/149958976-2bf13938-8094-41b8-afaf-ff105550240d.png)

Void Spirit:
![image](https://user-images.githubusercontent.com/36037203/149959098-e2dca042-76c9-4cfe-af4a-cdc15d6eb965.png)

Ember Spirit:
![image](https://user-images.githubusercontent.com/36037203/149959200-30e40865-e87f-4072-94ac-6cdadc1bd91c.png)

**Comment by ducbh62git** [comment]
This causes by Rubik's particle effect 
You can disable it by doing this way: **Handy Injection** >> **Used Item Database** >> **Right click on Rubik's Arcana** >> **Toggle Particle Effects Extraction**

By the way, how can you still use this tool when Valve adding VAC ban ?

**Comment by ducbh62git** [comment]
@lamdepzaihn98 are you using the dota2 latest version ?

**Comment by lamdepzaihn98** [comment]
> @lamdepzaihn98 are you using the dota2 latest version ?

Definitely, I always turn-on autoupdate option on steam app
