### ISSUE TITLE
Miss this tool so much

### ISSUE THREAD

**Issue by ducbh62git** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#39]
After Valve adding VAC to Dota2. I can't use this tool anymore. 
I just play in bot mode and enjoy the skin.
Does someone has the solution to use this tool ?

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
VAC notification has now been fixed, update DOTA2 MOD Master to v2.10.0 .
