### ISSUE TITLE
ANTI VAC

### ISSUE THREAD

**Issue by teddfrandell19** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#40]
Can anyone share a fix for this? I really missed playing with great looking skins,

**Comment by quishyy** [comment]
Hi, there is a fix, that disables vac message, but it requires special gameinfo.gi, that made specially for D2MO (Dota 2 Mod Organizer, and you don't need to use it), i'm playing with mods for almost month, and everything is working. You can download it here: https://www.mediafire.com/file/0fe3799qegsag0o/gameinfo.gi/file . Also make sure you'll instal D2MO, you don't need to install every mod through this app, but it will make base folder for mods in your dota directory.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
VAC notification has now been fixed, update DOTA2 MOD Master to v2.10.0 .

**Comment by quishyy** [comment]
> VAC notification has now been fixed, update DOTA2 MOD Master to v2.10.0 .

Thank you, for your awesome work!
