### ISSUE TITLE
Fix for VAC message

### ISSUE THREAD

**Issue by quishyy** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#41]
Hi, recently i found a fix, that disables vac message, but it requires special gameinfo.gi, that made specially for D2MO (Dota 2 Mod Organizer), i'm playing with mods for a while, and everything is working. You can download it from here: https://vk.com/topic-178507216_39493681 (check screenshot below) . Also make sure you'll install D2MO, you don't need to install every mod through this app, but it will make base folder for mods in your dota directory.
you can download D2MO here: https://www.mediafire.com/file/ehz2b3j29brr2hu/D2MO_v3.9_Full_Version.zip/file
Thanks to Amir4an for providing those file in his VK group.

I hope that it will help developers of this program, because i can't fix some scripts, due to installing many mods, that may rewrite items_game.txt file
![Screenshot_20220302_215216.jpg](https://user-images.githubusercontent.com/79086838/156409794-d962b3d4-2a7a-4d9c-a46f-683480b62cac.jpg)

**Comment by teddfrandell19** [comment]
thank you for this. can you show or tell us how to use this properly.

**Comment by quishyy** [comment]
> thank you for this. can you show or tell us how to use this properly.

sure, do you have discord or vk/telegram?

**Comment by teddfrandell19** [comment]
yes i do
Discord: lucifero#6803

**Comment by quishyy** [comment]
> 

sent invite, my is чуваk#9985

**Comment by ducbh62git** [comment]
> > 
> 
> sent invite, my is чуваk#9985

Can you please instruct us to make this mod work with your D2MO tool ?

**Comment by MaxKy-lip** [comment]
> Hi, recently i found a fix, that disables vac message, but it requires special gameinfo.gi, that made specially for D2MO (Dota 2 Mod Organizer), i'm playing with mods for a while, and everything is working. You can download it here: https://www.mediafire.com/file/0fe3799qegsag0o/gameinfo.gi/file . Also make sure you'll install D2MO, you don't need to install every mod through this app, but it will make base folder for mods in your dota directory. you can download D2MO here: https://www.mediafire.com/file/ehz2b3j29brr2hu/D2MO_v3.9_Full_Version.zip/file Thanks to Amir4an for providing those file in his VK group.
> 
> I hope that it will help developers of this program, because i can't fix some scripts, due to installing many mods, that may rewrite items_game.txt file

Please can you show us how to use it?

**Comment by MaxKy-lip** [comment]
Please can you show us how to use it?

**Comment by quishyy** [comment]
> Please can you show us how to use it?

add me on discord

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
VAC notification has now been fixed, update DOTA2 MOD Master to v2.10.0 .
