### ISSUE TITLE
Hi, we need your help 

### ISSUE THREAD

**Issue by quishyy** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#42]
if someone here knows Aldrin's social media accounts (discord vk facebook twitter etc) please, send a message to him, to check github, because we need him

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
How can I help you?

**Comment by quishyy** [comment]
> How can I help you?

by "we need your help" i meant that we need your tool, it's quite hard to extract files and work with scripts manually to make everything work, and your tool is best for modding

**Comment by quishyy** [comment]
> How can I help you?

Also, i have one question, can i use my own items_game.txt as a base? Mine contains some replacements such as sf arcana, and pa arcana, so i'm curious if i can use my items_game.txt and not standard one, because i want new mods and old in one script file.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
> > How can I help you?
> 
> Also, i have one question, can i use my own items_game.txt as a base? Mine contains some replacements such as sf arcana, and pa arcana, so i'm curious if i can use my items_game.txt and not standard one, because i want new mods and old in one script file.

This was requested long ago. Although due to some unexplored risks of using a custom items_game.txt, I still remain unsure if it's really worth trying. Although as how I see that you all have the same opinions about why it should be implemented, I'll try to implement it on the next version.

**Comment by quishyy** [comment]
> > > How can I help you?
> > 
> > Also, i have one question, can i use my own items_game.txt as a base? Mine contains some replacements such as sf arcana, and pa arcana, so i'm curious if i can use my items_game.txt and not standard one, because i want new mods and old in one script file.
> 
> This was requested long ago. Although due to some unexplored risks of using a custom items_game.txt, I still remain unsure if it's really worth trying. Although as how I see that you all have the same opinions about why it should be implemented, I'll try to implement it on the next version.

I hope that you'll make that, good luck on that.
Thanks for replying
