### ISSUE TITLE
a question about 10 people online game and local robot game

### ISSUE THREAD

**Issue by GoldenAgeFlash** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#47]
hello author, I am very glad to use your fantastic tool, it's still effective in May, 2022, thanks for your masterpiece! But I found the facts that 

1. in 10 people online game and local robot game, everyone has the same skin as you modded since the mechanism of DOTA2-MOD-MASTER is to replace the DEFAULT SLOT skin with modded skin, right?
2. in 10 people online game, if someone has his own skins, our modded skins will be replaced by them in visual effect

What I want to know is that whether these facts are normal. HOPE YOU CAN REPLY ME. THANKS~

**Comment by ducbh62git** [comment]
I'm not the author but I use this tool for a while and get same result. So yes, you're right
