### ISSUE TITLE
Hola

### ISSUE THREAD

**Issue by persi127** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#5]
Acabo de enviar el correo con las fotos que me pidió, espero les llegue, si no me avisan para volver a enviarlas, gracias por si atención.

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Aún no he recibido su correo electrónico, intente reenviarlo nuevamente. Además, no abras varios temas. Solo responde [aquí](https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/issues/3)
-Google Translate
#3

**Comment by persi127** [comment]
Buenas noches, el problema es que los sets aparecen pero los efectos ambientales y partículas no lo hacen a pesar de marcar las casillas de la opción "statistics".
[Image]
[Image]
[Image]

________________________________
De: Aldrin John Olaer Manalansan <notifications@github.com>
Enviado: domingo, 1 de noviembre de 2020 7:19 p. m.
Para: Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master
Cc: persi127; Author
Asunto: Re: [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master] Hola (#5)


Aún no he recibido su correo electrónico, intente reenviarlo nuevamente. Además, no abras varios temas. Solo responde aquí<https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/issues/3>
-Google Translate
#3<https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/issues/3>

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
No adjuntó ninguna captura de pantalla.

¿Parece haber instalado otras modificaciones además de DOTA2 MOD Master? Prueba esto:
1. Abra Steam y haga clic derecho en DOTA 2, haga clic izquierdo en propiedades.
2. Vaya a "Archivos locales"> y luego haga clic en "Verificar la integridad de los archivos del juego". Restaurará todos los archivos de DOTA 2. Espere a que finalice la actualización.
3. Vaya a DOTA 2 MOD Master> Advanced> y luego haga clic en "Patch GameInfo.gi"
4. Abra DOTA 2, los efectos ambientales y de partículas no deberían funcionar.

Si aún no funciona, dímelo.

-Google Translate
