### ISSUE TITLE
Still Working?

### ISSUE THREAD

**Issue by Burn1k** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#54]
Is this still working? i've use this tool last year but i dont know if this is still going to work.

**Comment by killatapez** [comment]
It does, why didn't u just test it for yourself?

**Comment by Burn1k** [comment]
I tried this but I was stuck with "Extracting Library Files" about an hour ago

**Comment by banderitax5** [comment]
I have the same issue, i guess we'll have to wait for the next version

**Comment by Burn1k** [comment]
> I have the same issue, i guess we'll have to wait for the next version

i solved the issue i forgot  that i should download it as zip not by launcher only, you can download it by following this link

https://github.com/Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master/archive/refs/heads/master.zip

**Comment by killatapez** [comment]
> i solved the issue i forgot that i should download it as zip not by launcher only, you can download it by following this link

It works both way, it's the first load that's very long
