### ISSUE TITLE
Particle missing when using external files

### ISSUE THREAD

**Issue by Edan11** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#71]
when i use external files just (custom item game) for some item not show,
and the particle justt missing idk why,
but the external file work fine.

can anyone fix this problem ?

**Comment by Edan11** [comment]
![image](https://user-images.githubusercontent.com/105978141/192118699-f4e44eb6-e7b2-464d-8cd6-29a81670edd9.png)
with external files (custom item game.txt)

![image](https://user-images.githubusercontent.com/105978141/192118731-7cffced7-d4f2-4d21-8266-5234eeab9f39.png)
with handy injection (no particle around the hero)

**Comment by Cjdota2** [comment]
hello this is not related to your post but i would like to ask how you made the mod work?

**Comment by Edan11** [comment]
go to -handy injection
-Hero item Selection

choose hero what ever u want (double click name of the hero)
and mark the skin u want in the right menu
![image](https://user-images.githubusercontent.com/105978141/192134968-2a153e5b-5f0b-4835-9f4f-a9fe2f62832e.png)

and last just Inject All Activate ID

**Comment by Cjdota2** [comment]
i see thanks alot! but we encountered another problem. When we were downloading this mod the pak.01 was missing we have tried redownloading it and even turning off our windows defender or any anti-virus programs when downloading it and it was still missing. We also tried manually downloading each files seperately and putting them in folders but it unfortunately still didnt work. any ideas on how to fix this?

**Comment by backtwohome** [comment]
pak01_dir is only created on injection. It will be located in the Aldrin_Mods folder in the dota directory or in the "AJOM's DOTA2 MOD Master\Plugins\VPKCreator" folder if the Auto_Shutnik method is disabled

**Comment by backtwohome** [comment]
> when i use external files just (custom item game) for some item not show,
and the particle justt missing idk why,
but the external file work fine.

possibly missing the "visuals" line in the items. You can check it in items_game.txt. For example search for Mace of Aeons it should be number "15" and scroll down it should look like this
![unnamed](https://user-images.githubusercontent.com/114341054/192498577-53edec6c-079d-4fbd-bd9c-736b923970fb.png)
![unnamed2](https://user-images.githubusercontent.com/114341054/192498615-eded94f2-2649-4692-ada5-731ad7d00f13.png)

**Comment by Edan11** [comment]
> possibly missing the "visuals" line in the items. You can check it in items_game.txt. For example search for Mace of Aeons it should be number "15" and scroll down it should look like this

there is visual in line but still no particle idk why

![image](https://user-images.githubusercontent.com/105978141/192511749-7ad06a30-f53d-468a-a14c-e3a3c6dc13b0.png)
![image](https://user-images.githubusercontent.com/105978141/192511901-9f568c37-574f-4e11-ae2b-7e9b7225ff3f.png)

**Comment by Edan11** [comment]
if i not use item game.txt
![image](https://user-images.githubusercontent.com/105978141/192513987-afd91353-2af9-4d28-89fb-71cdf7a70869.png)
my pa will look like this 
and particle for mace of aeons its working

**Comment by backtwohome** [comment]
it's not number "15", it's number "7571" prefab should be "default_item". your number "15" is not patched, search "Faceless Void's Weapon" and just copy "visuals" from "7571" and replace "visuals" of number "15"

**Comment by Edan11** [comment]
![image](https://user-images.githubusercontent.com/105978141/192523452-f35c33eb-8d71-40fd-b6f5-630ad2073cbd.png)
its working now, thanks

**Comment by backtwohome** [comment]
was happy to help

**Comment by Cjdota2** [comment]
I see. then do you perhaps know a video or a guide on how to make the this mod work? we still have no idea how to install and make it work so sorry for the repeated questions.

**Comment by Edan11** [comment]
> I see. then do you perhaps know a video or a guide on how to make the this mod work? we still have no idea how to install and make it work so sorry for the repeated questions.

![image](https://user-images.githubusercontent.com/105978141/192586936-a95b573c-4e6f-4597-b152-8624cdb466d2.png)
mark (auto shutnik method)

then follow this video https://www.youtube.com/watch?v=-BETnaBBLME&t=25s&ab_channel=A.J.O.Manalansan

**Comment by Cjdota2** [comment]
Hello i watched the video and this error appeared. Any ideas on how this can be fixed? my system is a 64bit 
![image](https://user-images.githubusercontent.com/114237195/192593470-1db1b112-6d68-4b31-a951-8e0094c79495.png)

**Comment by Edan11** [comment]
change the path location in dota 2 mod master

u can check by right click dota2 in steam then properties 
there is local files menu and click browse

it will located to your dota 2 folder

**Comment by Cjdota2** [comment]
its working now thanks alot!. also can i know the recent version? i have 2.10 currently and was wondering if there was anything higher or a better version

**Comment by Cjdota2** [comment]
Hello sorry for questioning again but where can i find the skins? it seems to be empty so sorry again.

**Comment by Cjdota2** [comment]
also how can i like pick which heroes gets to have skins and which do not

**Comment by Edan11** [comment]
> also how can i like pick which heroes gets to have skins and which do not

at the -Used Item Database, there is skin u already pick u cant delete it and back to hero item selection to use other skins

**Comment by Cjdota2** [comment]
ty its working now. Can i also asked if this is bannable?

**Comment by Edan11** [comment]
i think its not , 
cuz i use it almost 2 month

**Comment by vannessqn** [comment]
> i think its not , cuz i use it almost 2 month

Hi I want to change the skin of my skin not default skin but I dont know how pls help

**Comment by Edan11** [comment]
u need to modify ur own item game.txt,
also u can combine it with external files

**Comment by vannessqn** [comment]
> u need to modify ur own item game.txt, also u can combine it with external files

can you show me examples of the 2 things you talking, can i get your discord for some questions, I dont have exp in this but I learn fast promise not bother you much ty

**Comment by Edan11** [comment]
u can modify item game.txt from the mod
at general menu
-main
code to inject ( what skin u want example mace of aeons)
inject to ( skin to replace example Ancient Link)

find the id at search menu
mace of aeon
![image](https://user-images.githubusercontent.com/105978141/200275580-64490ab8-22ce-44ae-8f50-9824ceb01138.png)

ancient link
![image](https://user-images.githubusercontent.com/105978141/200275673-07b56669-5e12-4492-a451-5ef25fcfca3c.png)

and back to general menu  - main
put id 
code to inject = 7571
inject to = 6280
and done just check the box,  u can right click for change style
![image](https://user-images.githubusercontent.com/105978141/200276133-ed03a447-d287-41d1-8b04-f72418569693.png)

**Comment by Edan11** [comment]
if u want to combine with handy injection u need to turn off auto shutnik method at advanced menu
and choose what skin u want then inject all activate.
that will be create seperated file at generated MOD ( your folder mod) just copy
to external files.

make folder at external files
![image](https://user-images.githubusercontent.com/105978141/200277527-26533924-2fda-4351-a834-f3eaaf61333d.png)
and put in to the folder

![image](https://user-images.githubusercontent.com/105978141/200277400-a3524d16-73c7-4e1f-b57a-72ce9f47c348.png)

open the mod again
go to general menu 
use ur saved database (code to inject - inject to)
go to external files
![image](https://user-images.githubusercontent.com/105978141/200278372-3a7c71e3-2814-4f56-b999-87b8476dc41c.png)
check external files item game txt and include external game files

**Comment by Edan11** [comment]
![image](https://user-images.githubusercontent.com/105978141/200279151-baf5df01-a5cd-49b9-96a3-3776cf4dff45.png)
to this 
![image](https://user-images.githubusercontent.com/105978141/200280342-7620b5af-389d-422e-9205-08a4ad246503.png)

for operation files at external files make sure move to top

sorry for bad english.

**Comment by vannessqn** [comment]
damn what a reply! you're a boss irl bruh, thank you man also your english is fine bro

**Comment by vannessqn** [comment]
also why do I need to combine with handy injection isnt the first way already cover default items if you want too?

**Comment by Edan11** [comment]
arcana and some immortal skin have bug so i need to change to replace trash skin

**Comment by Edan11** [comment]
for arcana es u need helm replace because in game will not show anything (bald es)

**Comment by vannessqn** [comment]
are you able to make Axe using only the immortal fists? Im doing both the inject to and external files way and he still using both fists + other weapon if he is picked by teammates or opponents

**Comment by Edan11** [comment]
check item game.txt maybe ur replace skin not patched correctly

**Comment by vannessqn** [comment]
ye I think the problem is not with axe only its like if any items has custom spells like immortals and arcanas it make all the server used that custom spells, like I inject the purple gun of sniper and now all sniper in the game use the purple effect of the gun too, idk how to resolve this maybe this is how its suppose to work? if you will please give me an example like how you edit to make the immortal purple sniper's gun custom shot effect stay with urself and not all sniper..

**Comment by Edan11** [comment]
that's how the mod it work

**Comment by vannessqn** [comment]
ok ty i understand so if you mod the custom effect all will use the custom effect because I guess the mod change to effect to default so everyone has it, lucky you here can you tell how to fix this? https://imgur.com/a/bnYHe8O

**Comment by Edan11** [comment]
open mod and go to migration menu
put ur item game.txt it will create new item game.txt  (without error)

search ur error in new item game.txt 
![image](https://user-images.githubusercontent.com/105978141/200844775-9a130032-7e95-4629-8353-9504e010d984.png)
winter_2022 copy from winter _2022 to down until its done. ( dont forget to see the name before winter_2022 
![image](https://user-images.githubusercontent.com/105978141/200848073-ef951ba6-6ee3-42b8-a7da-fc5d246dd9c1.png)
)

paste to ur old item game.txt after winter 2021 dota plus
![image](https://user-images.githubusercontent.com/105978141/200847779-f9195669-d3a2-4fc6-97c5-be5afb0e82fc.png)

**Comment by vannessqn** [comment]
thanks this make me discover the names of the collector sets I tried to use it with inject and its work too
