### ISSUE TITLE
Problem in Handy Injection

### ISSUE THREAD

**Issue by igcarvalhaes** [Aldrin-John-Olaer-Manalansan/DOTA-2-MOD-Master#8]
I am using the latest version of your app. When I inject all actived ID's using your latest database the program doesn't finish modding.  It stays in Shutnik Method: Creating pak01_dir.vpk forever.

Here is the link of the printscreen I made to show you exactly what happens.
https://ibb.co/ByK0ggR

**Comment by Aldrin-John-Olaer-Manalansan** [comment]
Fixed.
